/**
 * Central error / reason codes (common pack).
 * Expand as modules land; do not use banned yield vocabulary.
 */
export enum AstErrorCode {
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_DECIMAL = 'INVALID_DECIMAL',
  INVALID_INSTITUTION_CODE = 'INVALID_INSTITUTION_CODE',
  INVALID_PROCESS_ID = 'INVALID_PROCESS_ID',
  INVARIANT_BROKEN = 'INVARIANT_BROKEN',
  POT_NOT_VERIFIED = 'POT_NOT_VERIFIED',
  POT_CRITERIA_FAILED = 'POT_CRITERIA_FAILED',
  POT_EXPIRED = 'POT_EXPIRED',
  POT_DOUBLE_CONFIRM = 'POT_DOUBLE_CONFIRM',
  NODECHAIN_APPEND_UNAUTHORIZED = 'NODECHAIN_APPEND_UNAUTHORIZED',
  NODECHAIN_APPEND_FAILED = 'NODECHAIN_APPEND_FAILED',
  QUALIFIED_SIGNATURE_REQUIRED = 'QUALIFIED_SIGNATURE_REQUIRED',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  INSUFFICIENT_RESERVE = 'INSUFFICIENT_RESERVE',
  ADMIN_MINT_FORBIDDEN = 'ADMIN_MINT_FORBIDDEN',
  KILL_SWITCH_ACTIVE = 'KILL_SWITCH_ACTIVE',
}

export type PotCriteriaId = 'P1' | 'P2' | 'P3' | 'P4';

export type InvariantId =
  | 'I1'
  | 'I2'
  | 'I3'
  | 'I4'
  | 'I5'
  | 'I6'
  | 'I7'
  | 'I8'
  | 'I9';
