#!/usr/bin/env bash
# E2 — materialize .env.production from example + data/institution-secrets.json
# Never commits. Overwrites .env.production after backup.
#
# Usage: npm run cutover:env
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXAMPLE="$ROOT/.env.production.example"
OUT="$ROOT/.env.production"
SECRETS="${AST_INSTITUTION_SECRETS_FILE:-$ROOT/data/institution-secrets.json}"
HOST="${AST_PUBLIC_HOST:-}"

[[ -f "$EXAMPLE" ]] || { echo "missing $EXAMPLE"; exit 1; }

if [[ ! -f "$SECRETS" ]]; then
  echo "No $SECRETS — run: bash scripts/setup-institution-secrets.sh --random-salt"
  exit 1
fi

# Compact JSON one line for env
SECRETS_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1])),separators=(",",":")))' "$SECRETS")"
# Prefer first institution token as core shared secret if not set
CORE_TOKEN="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d[0].get("token",""))' "$SECRETS")"

if [[ -f "$OUT" ]]; then
  bak="$OUT.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUT" "$bak"
  echo "Backed up previous → $bak"
fi

{
  echo "# Generated by scripts/cutover-env.sh — DO NOT COMMIT"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  # base from example, skip old secrets lines we rewrite
  grep -vE '^(AST_INSTITUTION_SECRETS_JSON|AST_INSTITUTION_TOKEN|AST_ALLOW_DEMO|NODE_ENV|AST_PUBLIC_HOST|NEXT_PUBLIC_PORTAL_API_URL)=' "$EXAMPLE" || true
  echo ""
  echo "NODE_ENV=production"
  echo "AST_ALLOW_DEMO=0"
  echo "AST_REQUIRE_INSTITUTION_AUTH=1"
  echo "AST_LOG_JSON=1"
  echo "AST_INSTITUTION_TOKEN=${AST_INSTITUTION_TOKEN:-$CORE_TOKEN}"
  echo "AST_INSTITUTION_SECRETS_JSON=${SECRETS_JSON}"
  if [[ -n "$HOST" ]]; then
    echo "AST_PUBLIC_HOST=$HOST"
    echo "NEXT_PUBLIC_PORTAL_API_URL=https://${HOST}"
  else
    echo "# AST_PUBLIC_HOST=ast.example.com"
    echo "# NEXT_PUBLIC_PORTAL_API_URL=https://ast.example.com"
  fi
  echo "# Optional data plane:"
  echo "# DATABASE_URL=postgres://ast:SECRET@postgres:5432/ast_index"
  echo "# REDIS_URL=redis://redis:6379"
  echo "# AST_EVENT_OUT_URL="
} > "$OUT"

chmod 600 "$OUT" 2>/dev/null || true
echo "Wrote $OUT (gitignored)"
echo "Review tokens, then: npm run cutover:preflight"
