#!/usr/bin/env bash
# Permanent domain WITHOUT Cloudflare DNS.
# DNS at Namecheap (or any registrar): A record → your public IP.
# This Mac: Caddy reverse-proxy HTTPS → Portal UI :3200 (auto Let's Encrypt).
#
# Prerequisites:
#   - A (and optional www A/CNAME) points to this house public IP
#   - Router port-forward: TCP 80 and 443 → this Mac LAN IP
#   - Stack running: bash scripts/home-up.sh
#
# Usage:
#   bash scripts/domain-proxy-up.sh
#   AST_PUBLIC_DOMAIN=arosfinancialcore.com bash scripts/domain-proxy-up.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG_DIR="${AST_HOME_LOG_DIR:-$ROOT/.home-run}"
ROOT_BIN="$LOG_DIR/bin"
mkdir -p "$LOG_DIR"

DOMAIN="${AST_PUBLIC_DOMAIN:-arosfinancialcore.com}"
EXTRA="${AST_PUBLIC_WWW:-www.${DOMAIN}}"
UI_URL="${AST_HOME_UI_URL:-http://127.0.0.1:3200}"
EMAIL="${AST_TLS_EMAIL:-info@${DOMAIN}}"
CADDYFILE="${AST_CADDYFILE:-$LOG_DIR/Caddyfile}"
CADDY_DATA="${AST_CADDY_DATA:-$LOG_DIR/caddy-data}"
CADDY_CONFIG="${AST_CADDY_CONFIG:-$LOG_DIR/caddy-config}"

resolve_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    command -v caddy
  elif [[ -x "$ROOT_BIN/caddy" ]]; then
    echo "$ROOT_BIN/caddy"
  else
    echo "ERROR: caddy not found. Install: brew install caddy" >&2
    echo "  or place binary at $ROOT_BIN/caddy" >&2
    exit 1
  fi
}

CADDY="$(resolve_caddy)"
echo "==> caddy: $CADDY ($("$CADDY" version 2>&1 | head -1))"
echo "==> domain: $DOMAIN (+ $EXTRA)"
echo "==> backend: $UI_URL"

# Wait for UI
ok=0
for i in $(seq 1 30); do
  if curl -sf "$UI_URL" >/dev/null 2>&1; then ok=1; break; fi
  sleep 0.5
done
if [[ "$ok" -ne 1 ]]; then
  echo "WARN: UI not up at $UI_URL — start with: bash scripts/home-up.sh"
fi

# Stop previous caddy / quick tunnel conflict on 80/443
if [[ -f "$LOG_DIR/caddy.pid" ]]; then
  old="$(cat "$LOG_DIR/caddy.pid" || true)"
  if [[ -n "${old:-}" ]] && kill -0 "$old" 2>/dev/null; then
    echo "==> Stopping previous caddy pid $old"
    kill "$old" 2>/dev/null || true
    sleep 0.5
  fi
  rm -f "$LOG_DIR/caddy.pid"
fi

# Free 80/443 if something else holds them
for port in 80 443; do
  pids="$(lsof -tiTCP:$port -sTCP:LISTEN 2>/dev/null || true)"
  if [[ -n "${pids:-}" ]]; then
    echo "==> Freeing :$port ($pids)"
    # shellcheck disable=SC2086
    kill $pids 2>/dev/null || true
    sleep 0.3
  fi
done

mkdir -p "$CADDY_DATA" "$CADDY_CONFIG"

cat >"$CADDYFILE" <<EOF
# Generated by domain-proxy-up.sh — local only, not committed
{
	email ${EMAIL}
}

${DOMAIN}, ${EXTRA} {
	encode gzip
	reverse_proxy ${UI_URL}
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
	}
	log {
		output file ${LOG_DIR}/caddy-access.log
	}
}
EOF

echo "==> Wrote $CADDYFILE"
echo "==> Starting Caddy (Let's Encrypt will need :80 open from internet)"

# Caddy needs bind on 80/443 — may need elevated privileges on macOS
run_caddy() {
  nohup env \
    XDG_DATA_HOME="$CADDY_DATA" \
    XDG_CONFIG_HOME="$CADDY_CONFIG" \
    "$CADDY" run --config "$CADDYFILE" --adapter caddyfile \
    >"$LOG_DIR/caddy.log" 2>&1 &
  echo $! >"$LOG_DIR/caddy.pid"
}

if [[ "$(id -u)" -eq 0 ]]; then
  run_caddy
else
  # Try without sudo first (if previously allowed)
  if run_caddy; then
    sleep 1
    if ! kill -0 "$(cat "$LOG_DIR/caddy.pid")" 2>/dev/null; then
      echo "==> Non-root bind failed; will need privileges for :80/:443"
      rm -f "$LOG_DIR/caddy.pid"
      # Leave instructions — cannot sudo non-interactively reliably
      echo ""
      echo "Run once with network bind privilege:"
      echo "  sudo bash scripts/domain-proxy-up.sh"
      echo "Or grant caddy the capability and re-run."
      exit 1
    fi
  fi
fi

sleep 2
if ! kill -0 "$(cat "$LOG_DIR/caddy.pid" 2>/dev/null || echo 0)" 2>/dev/null; then
  echo "ERROR: caddy exited. Log:"
  tail -40 "$LOG_DIR/caddy.log" || true
  echo ""
  echo "Common fixes:"
  echo "  - Router: forward TCP 80 and 443 → this Mac ($(ipconfig getifaddr en0 2>/dev/null || echo LAN-IP))"
  echo "  - DNS A ${DOMAIN} must equal this public IP"
  echo "  - sudo bash scripts/domain-proxy-up.sh   # bind :80/:443"
  exit 1
fi

PUBLIC="https://${DOMAIN}"
echo "$PUBLIC" >"$LOG_DIR/public-url.txt"

echo ""
echo "========================================"
echo "  DOMAIN (no Cloudflare)"
echo "  $PUBLIC"
echo "  https://${EXTRA}"
echo "========================================"
echo "  Backend: $UI_URL"
echo "  Logs:    tail -f $LOG_DIR/caddy.log"
echo "  Stop:    bash scripts/home-down.sh"
echo ""
echo "  Namecheap DNS (you control):"
echo "    A     @     → YOUR_PUBLIC_IP"
echo "    A     www   → YOUR_PUBLIC_IP   (or CNAME www → @)"
echo "  Router: TCP 80 + 443 → Mac LAN"
