#!/usr/bin/env bash
# One-time: bind permanent domain → home Portal UI via Cloudflare Named Tunnel.
#
# Prerequisites (your side):
#   1. Domain registered (e.g. arosfinancialcore.com)
#   2. Domain added in Cloudflare Dashboard (free plan OK)
#      → Nameservers at registrar must be Cloudflare NS (status Active)
#   3. This Mac can open a browser for Cloudflare login once
#
# Usage:
#   bash scripts/domain-tunnel-setup.sh
#   bash scripts/domain-tunnel-setup.sh arosfinancialcore.com
#
# After setup:
#   bash scripts/home-up.sh
#   bash scripts/domain-tunnel-up.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG_DIR="${AST_HOME_LOG_DIR:-$ROOT/.home-run}"
ROOT_BIN="$LOG_DIR/bin"
CFG_DIR="${CLOUDFLARED_CONFIG_DIR:-$HOME/.cloudflared}"
STATE_DIR="$LOG_DIR/cloudflare"
mkdir -p "$LOG_DIR" "$STATE_DIR" "$CFG_DIR"

DOMAIN="${1:-${AST_PUBLIC_DOMAIN:-arosfinancialcore.com}}"
TUNNEL_NAME="${AST_TUNNEL_NAME:-ast-portal}"
UI_URL="${AST_HOME_UI_URL:-http://127.0.0.1:3200}"
# Optional extra hostnames (space-separated), default: apex + www
EXTRA_HOSTS="${AST_TUNNEL_EXTRA_HOSTS:-www.${DOMAIN}}"

resolve_cloudflared() {
  local bin
  bin="$(command -v cloudflared 2>/dev/null || true)"
  if [[ -z "$bin" && -x "$ROOT_BIN/cloudflared" ]]; then
    bin="$ROOT_BIN/cloudflared"
  fi
  if [[ -z "$bin" ]]; then
    echo "==> cloudflared not found — downloading official binary..."
    mkdir -p "$ROOT_BIN"
    ARCH="$(uname -m)"
    if [[ "$ARCH" == "arm64" ]]; then
      CF_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz"
    else
      CF_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz"
    fi
    curl -fsSL -o /tmp/cloudflared.tgz "$CF_URL"
    tar -xzf /tmp/cloudflared.tgz -C "$ROOT_BIN"
    chmod +x "$ROOT_BIN/cloudflared"
    bin="$ROOT_BIN/cloudflared"
  fi
  echo "$bin"
}

CLOUDFLARED="$(resolve_cloudflared)"
echo "==> cloudflared: $CLOUDFLARED ($("$CLOUDFLARED" --version 2>&1 | head -1))"
echo "==> Domain:      $DOMAIN"
echo "==> Tunnel name: $TUNNEL_NAME"
echo "==> Local UI:    $UI_URL"
echo ""

# --- Step 1: login (cert.pem) ---
if [[ ! -f "$CFG_DIR/cert.pem" ]]; then
  echo "========================================"
  echo " Cloudflare login required (once)"
  echo " A browser window will open."
  echo " Select the zone that owns: $DOMAIN"
  echo "========================================"
  echo ""
  "$CLOUDFLARED" tunnel login
  if [[ ! -f "$CFG_DIR/cert.pem" ]]; then
    echo "ERROR: login did not produce $CFG_DIR/cert.pem"
    echo "Add the domain in Cloudflare Dashboard first, then re-run this script."
    exit 1
  fi
  echo "==> Login OK"
else
  echo "==> Already logged in ($CFG_DIR/cert.pem)"
fi

# --- Step 2: create named tunnel if missing ---
TUNNEL_ID=""
if "$CLOUDFLARED" tunnel list 2>/dev/null | grep -qE "[[:space:]]${TUNNEL_NAME}[[:space:]]"; then
  TUNNEL_ID="$("$CLOUDFLARED" tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')"
  echo "==> Tunnel exists: $TUNNEL_NAME ($TUNNEL_ID)"
else
  echo "==> Creating tunnel: $TUNNEL_NAME"
  CREATE_OUT="$("$CLOUDFLARED" tunnel create "$TUNNEL_NAME" 2>&1)" || true
  echo "$CREATE_OUT"
  TUNNEL_ID="$("$CLOUDFLARED" tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')"
  if [[ -z "$TUNNEL_ID" ]]; then
    # parse "Created tunnel ... with id <uuid>"
    TUNNEL_ID="$(echo "$CREATE_OUT" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)"
  fi
fi

if [[ -z "$TUNNEL_ID" ]]; then
  echo "ERROR: could not resolve tunnel id for $TUNNEL_NAME"
  "$CLOUDFLARED" tunnel list || true
  exit 1
fi

CRED_FILE="$CFG_DIR/${TUNNEL_ID}.json"
if [[ ! -f "$CRED_FILE" ]]; then
  # credentials may live under alternate path after create
  ALT="$(ls "$CFG_DIR"/*.json 2>/dev/null | head -1 || true)"
  if [[ -n "${ALT:-}" && ! -f "$CRED_FILE" ]]; then
    echo "WARN: expected credentials at $CRED_FILE — found $ALT"
    CRED_FILE="$ALT"
  else
    echo "ERROR: missing credentials file $CFG_DIR/${TUNNEL_ID}.json"
    echo "Try: cloudflared tunnel delete $TUNNEL_NAME && re-run setup"
    exit 1
  fi
fi

# --- Step 3: write config.yml ---
CONFIG_FILE="$CFG_DIR/config.yml"
HOSTS=("$DOMAIN")
# shellcheck disable=SC2206
EXTRA_ARR=($EXTRA_HOSTS)
for h in "${EXTRA_ARR[@]:-}"; do
  [[ -n "$h" && "$h" != "$DOMAIN" ]] && HOSTS+=("$h")
done

{
  echo "# Generated by scripts/domain-tunnel-setup.sh — do not commit secrets"
  echo "tunnel: $TUNNEL_ID"
  echo "credentials-file: $CRED_FILE"
  echo ""
  echo "ingress:"
  for h in "${HOSTS[@]}"; do
    echo "  - hostname: $h"
    echo "    service: $UI_URL"
  done
  echo "  - service: http_status:404"
} >"$CONFIG_FILE"

echo "==> Wrote $CONFIG_FILE"
cat "$CONFIG_FILE"
echo ""

# --- Step 4: DNS routes (Cloudflare-managed zone) ---
echo "==> Routing DNS (CNAME → tunnel) for hostnames..."
for h in "${HOSTS[@]}"; do
  echo "    → $h"
  if ! "$CLOUDFLARED" tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$h" 2>&1; then
    echo "    WARN: route dns failed for $h"
    echo "    Ensure $DOMAIN is an Active zone in this Cloudflare account."
    echo "    Or add manually in Dashboard:"
    echo "      Type CNAME  Name ${h%.$DOMAIN} (or @)  Target ${TUNNEL_ID}.cfargotunnel.com  Proxied ON"
  fi
done

# --- Step 5: persist local state for domain-tunnel-up ---
echo "$DOMAIN" >"$STATE_DIR/domain.txt"
echo "$TUNNEL_NAME" >"$STATE_DIR/tunnel-name.txt"
echo "$TUNNEL_ID" >"$STATE_DIR/tunnel-id.txt"
echo "https://${DOMAIN}" >"$LOG_DIR/public-url.txt"
echo "$CONFIG_FILE" >"$STATE_DIR/config-path.txt"

echo ""
echo "========================================"
echo "  SETUP COMPLETE"
echo "  Permanent URL: https://${DOMAIN}"
echo "  (also: https://www.${DOMAIN} if routed)"
echo "========================================"
echo ""
echo "Next:"
echo "  1) bash scripts/home-up.sh          # if stack not running"
echo "  2) bash scripts/domain-tunnel-up.sh # keep Mac awake / process alive"
echo ""
echo "Optional: remove old A-record to home IP ($DOMAIN → 46.x) in Cloudflare"
echo "so only the tunnel CNAME remains (route dns usually overwrites)."
echo ""
echo "Stop: bash scripts/home-down.sh"
