#!/usr/bin/env tsx
/**
 * D4 — generate demo CA + leaf + detached signature over a sample package hash.
 * Requires openssl on PATH. Material is for local tests only — not a national CA.
 *
 * Usage: npm run demo:x509-package
 */
import { createHash, createSign } from 'crypto';
import { execFileSync } from 'child_process';
import { promises as fs } from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'fixtures', 'x509-demo');
const TRUST = path.join(OUT, 'trust');

function openssl(args: string[], cwd?: string) {
  execFileSync('openssl', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
}

async function main() {
  await fs.mkdir(TRUST, { recursive: true });

  const caKey = path.join(OUT, 'demo-ca.key');
  const caPem = path.join(TRUST, 'demo-ca.pem');
  const leafKey = path.join(OUT, 'leaf.key');
  const leafCsr = path.join(OUT, 'leaf.csr');
  const leafPem = path.join(OUT, 'leaf.pem');
  const extFile = path.join(OUT, 'leaf.ext');

  // CA
  openssl([
    'req',
    '-x509',
    '-newkey',
    'rsa:2048',
    '-keyout',
    caKey,
    '-out',
    caPem,
    '-days',
    '3650',
    '-nodes',
    '-subj',
    '/CN=AST Demo CA/O=AST Pilot/C=GE',
  ]);

  // Leaf CSR (institution PILOT)
  openssl([
    'req',
    '-newkey',
    'rsa:2048',
    '-keyout',
    leafKey,
    '-out',
    leafCsr,
    '-nodes',
    '-subj',
    '/CN=PILOT/O=Pilot Institution/C=GE',
  ]);

  await fs.writeFile(
    extFile,
    'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,nonRepudiation\nextendedKeyUsage=emailProtection,codeSigning\n',
  );

  openssl([
    'x509',
    '-req',
    '-in',
    leafCsr,
    '-CA',
    caPem,
    '-CAkey',
    caKey,
    '-CAcreateserial',
    '-out',
    leafPem,
    '-days',
    '825',
    '-extfile',
    extFile,
  ]);

  // Sample package hash (same shape as documentPackageHash)
  const sampleBytes = Buffer.from('AST-D4-demo-package-bytes-v1');
  const hashHex = createHash('sha256').update(sampleBytes).digest('hex');
  const hashBytes = Buffer.from(hashHex, 'hex');

  const keyPem = await fs.readFile(leafKey, 'utf8');
  const signer = createSign('RSA-SHA256');
  signer.update(hashBytes);
  signer.end();
  const signatureBase64 = signer.sign(keyPem).toString('base64');

  const sample = {
    documentPackageHash: hashHex,
    signatureBase64,
    signerCertificatePem: await fs.readFile(leafPem, 'utf8'),
    trustAnchorPem: await fs.readFile(caPem, 'utf8'),
    mode: 'x509_detached',
    note: 'Demo only — not a national QES. Signed message = 32 raw hash bytes, RSA-SHA256.',
  };
  await fs.writeFile(path.join(OUT, 'sample-detached.json'), JSON.stringify(sample, null, 2) + '\n');

  await fs.writeFile(
    path.join(OUT, 'README.md'),
    `# X.509 demo material (D4)

**Not production / not a national CA.** Regenerated by \`npm run demo:x509-package\`.

| File | Role |
|------|------|
| \`trust/demo-ca.pem\` | Trust anchor for local edge |
| \`leaf.pem\` | Signer certificate (CN=PILOT) |
| \`leaf.key\` | Demo private key (local only) |
| \`sample-detached.json\` | Hash + signature + cert for API tests |

Do not use these keys outside pilot fixtures.
`,
  );

  // Restrictive perms on keys
  await fs.chmod(caKey, 0o600).catch(() => undefined);
  await fs.chmod(leafKey, 0o600).catch(() => undefined);

  console.log('D4 x509 demo package written to', OUT);
  console.log('  trust:', caPem);
  console.log('  leaf:', leafPem);
  console.log('  sample hash:', hashHex.slice(0, 16) + '…');
  console.log('  sample-detached.json ready');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
