/** Stable PoT reason codes — see docs/layers/04_ProofOfTransaction/01_model/reason-codes.md */

export const PotReason = {
  P1_INSTITUTION_NOT_ALLOWLISTED: 'P1_INSTITUTION_NOT_ALLOWLISTED',
  P1_CONTEXT_INVALID: 'P1_CONTEXT_INVALID',
  P2_STAGES_INCOMPLETE: 'P2_STAGES_INCOMPLETE',
  P3_STATES_NOT_RECORDED: 'P3_STATES_NOT_RECORDED',
  P3_MISSING_PROCESS_OPEN: 'P3_MISSING_PROCESS_OPEN',
  P4_DOCUMENTS_MISSING: 'P4_DOCUMENTS_MISSING',
  P4_SIGNATURE_MISSING: 'P4_SIGNATURE_MISSING',
  P4_VALUATION_MISSING: 'P4_VALUATION_MISSING',
  P4_HOLDER_MISSING: 'P4_HOLDER_MISSING',
  P4_PROCESS_RULES_FAILED: 'P4_PROCESS_RULES_FAILED',
  QUORUM_SHORT: 'QUORUM_SHORT',
  QUORUM_K_BELOW_MIN: 'QUORUM_K_BELOW_MIN',
  POT_TIMEOUT: 'POT_TIMEOUT',
  POT_DOUBLE_CONFIRM: 'POT_DOUBLE_CONFIRM',
  POT_ALREADY_FINAL: 'POT_ALREADY_FINAL',
  POT_INVALID_INPUT: 'POT_INVALID_INPUT',
  ATTESTATION_MISSING: 'ATTESTATION_MISSING',
  ATTESTATION_DUPLICATE: 'ATTESTATION_DUPLICATE',
  ATTESTATION_NOT_ELIGIBLE: 'ATTESTATION_NOT_ELIGIBLE',
  ATTESTATION_BAD_ALG: 'ATTESTATION_BAD_ALG',
  ATTESTATION_BAD_SIG: 'ATTESTATION_BAD_SIG',
  ATTESTATION_INSUFFICIENT: 'ATTESTATION_INSUFFICIENT',
  CHALLENGE_OPEN: 'CHALLENGE_OPEN',
  VALIDATOR_SET_EMPTY: 'VALIDATOR_SET_EMPTY',
} as const;

export type PotReasonCode = (typeof PotReason)[keyof typeof PotReason] | string;

export function stageMissing(stage: string): string {
  return `P2_STAGE_MISSING:${stage}`;
}
